#DATABASE :
spring.datasource.url = ${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name = org.postgresql.Driver
spring.jpa.hibernate.ddl-auto = validate
spring.jpa.show-sql = true

#Flyway:

spring.flyway.enabled = true
spring.flyway.locations = classpath:db/migration

#Redis :
spring.data.redis.url = ${REDIS_URL}

#JWT :

jwt.secret = ${JWT_SECRET}
jwt.expiration = 86400000

#Backblaze :
app.storage.endpoint=${B2_ENDPOINT}
app.storage.region=${B2_REGION}
app.storage.access-key=${B2_KEY_ID}
app.storage.secret-key=${B2_APP_KEY}
app.storage.bucket=${B2_BUCKET}

#App :
app.frontend.url=${FRONTEND_URL:http://localhost:5173}
